import "../../globals.css";
import NavbarTwo from "../../../components/NavbarTwo";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavbarTwo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
